name: Script Submission Request
description: Use this template for submitting a script to the repository.
title: "[Script Submission]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to a new script to the library!
        Once filled out, someonde from the team will review your submission and get back to you as soon as possible.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a description (details) about what the script will do?
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What type of script (PowerShell or Console App)?
      options:
        - PowerShell
        - Console App
    validations:
      required: true
  - type: textarea
    id: tags
    attributes:
      label: Add some tags (keywords) to help others find your script (separate by comma)
      description: Please add some keywords (SharePoint, MS Teams, Azure AD, ...).
